name = "VisualStringDistances"
uuid = "089bb0c6-1854-47b9-96f7-327dbbe09dca"
authors = ["Eric P. Hanson"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnbalancedOptimalTransport = "6f61b460-fd45-461a-bdf7-98edd72e362f"

[compat]
CSV = "0.5, 0.7"
StaticArrays = "0.12"
UnbalancedOptimalTransport = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
